baseURL: "https://prateeksrivastava.com/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Prateek's Website
copyright: Prateek Srivastava
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: G-ZWYREN3YMD

minify:
  disableXML: true
  minifyOutput: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: apple-touch-icon.png
    iconHeight: 35

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - identifier: home
                  name: Home
                  url: /
                  weight: 5
                - name: About
                  url: about/
                  weight: 10
                - name: Blog
                  url: posts/
                  weight: 20
                #- identifier: categories
                #  name: Categories
                #  url: categories/
                #  weight: 30
                - identifier: tags
                  name: Tags
                  url: tags/
                  weight: 40
                - identifier: archives
                  name: Archives
                  url: archives/
                  weight: 50
                - name: Search
                  url: search/
                  weight: 60
                - name: Contact
                  url: contact/
                  weight: 80

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Prateek's website"
    author: Prateek Srivastava
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    #defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    ShareButtons: ["linkedin", "twitter", "mastodon", "reddit", "facebook","whatsapp"]
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true
    displayFullLangName: true
    images: ["papermod-cover.png"]
    profileMode:
      enabled: true # needs to be explicitly set
      title: "Prateek Srivastava"
      subtitle: "Technology Leader, Strategic Planner, Traveler, Science Enthusiast, Family Man."
      imageUrl: "images/author.jpg"
      imageWidth: 300
      imageHeight: 300
      imageTitle: Prateek's Profile image
      buttons:
        - name: Posts
          url: posts
        - name: About
          url: /pages/about

    socialIcons:
        - name: Rss
          url: "index.xml"
        - name: Twitter
          url: "https://twitter.com/prateek"
        - name: Mastodon
          url: "https://oslo.town/@prateek"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/prateeksrivastava"


assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

